apiVersion: v1
kind: Secret
metadata:
    name: url-shortener-secret
type: Opaque
data:
    mongo-root-uri: bW9uZ29kYjovL2FkbWluOmFkbWluQGNsdXN0ZXIwLXNoYXJkLTAwLTAwLnh4cm56Lm1vbmdvZGIubmV0OjI3MDE3LGNsdXN0ZXIwLXNoYXJkLTAwLTAxLnh4cm56Lm1vbmdvZGIubmV0OjI3MDE3LGNsdXN0ZXIwLXNoYXJkLTAwLTAyLnh4cm56Lm1vbmdvZGIubmV0OjI3MDE3L215Rmlyc3REYXRhYmFzZT9zc2w9dHJ1ZSZyZXBsaWNhU2V0PWF0bGFzLWhkazN1eC1zaGFyZC0wJmF1dGhTb3VyY2U9YWRtaW4mcmV0cnlXcml0ZXM9dHJ1ZSZ3PW1ham9yaXR5