apiVersion: v1
kind: Secret
metadata:
    name: url-shortener-secret
type: Opaque
data:
    mongo-root-user: dXNlcm5hbWU=
    mongo-root-password: cGFzc3dvcmQ=
    mongo-root-ip: MTAuMTA4LjIyNC4xMTQ=
    mongo-root-port: MjcwMTc=
