apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener-deployment
  namespace: urlshortener
  labels:
    app: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
      - name: url-shortener
        image: ashwin901/url-shortener
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: MONGO_USER
          valueFrom: 
            secretKeyRef:
              name: url-shortener-secret
              key: mongo-root-user
        - name: MONGO_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: url-shortener-secret
              key: mongo-root-password
        - name: MONGO_IP
          valueFrom: 
            secretKeyRef:
              name: url-shortener-secret
              key: mongo-root-ip
        - name: MONGO_PORT
          valueFrom: 
            secretKeyRef:
              name: url-shortener-secret
              key: mongo-root-port
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
  namespace: urlshortener
spec:
  selector:
    app: url-shortener
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
